# Generated by Django 4.2.15 on 2024-08-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('image', models.ImageField(upload_to='media')),
                ('desc', models.TextField()),
                ('hp', models.TextField()),
                ('model', models.CharField(max_length=50, null=True, unique=True)),
                ('mi', models.TextField()),
            ],
        ),
    ]
