# Generated by Django 4.2.15 on 2024-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
